### ISSUE TITLE
Stock Ringtones, Alarm, Notifications not selectable

### ISSUE THREAD

**Issue by killigrew** [CyanogenDefy/android_device_motorola_jordan#6]
Hi

All stock sounds that are placed in /system/media/audio/ do not appear in there respective menus.
Soundfiles that are placed on the sdcard appear without problem.
Don't know if its a codec, permission or another problem, but i hope it gets fixed before final release.
btw. it is present since beta4 when i started using cm7.

greetings

**Comment by martinml** [comment]
They appear and are selectable for me in RC0.

**Comment by sidez** [comment]
Hi, I've this same issue Only 3 options showing on settings->sound->ring tone
SILENCE, SHOCKING and WHISTLER nothing else.

Same happens on notifications, only 3 options there, not the same three noted above.

regards

**Comment by charlie2alpha** [comment]
I'm confirming this, have the same problem for some time now, just never bothered much since I use my own ringtones. It is a bug though, persists even after a wipe.

**Comment by maniac103** [comment]
Confirmed, will check into it.

**Comment by maniac103** [comment]
The root cause is that line:
D/MediaScanner( 2434): opendir /system/media/audio/alarms/Alarm_Beep_01.ogg/ failed, errno: 20

The media scanner for some reason thinks that Alarm_Beep_01.ogg is a directory, tries to open it, fails doing so (obviously) and aborts the scan because of that.
Now I 'just' need to find out why it thinks that file is a directory...

**Comment by maniac103** [comment]
Fixed: https://github.com/CyanogenDefy/android_frameworks_base/commit/7d354a3d2dc14d6095b6449ee983bbaad4786aae

Seemingly a long-standing bug in Android that only seems to trigger with the Defy's kernel.
