### ISSUE TITLE
big camera problem - pls quarx help me

### ISSUE THREAD

**Issue by gaubu84** [CyanogenDefy/android_device_motorola_jordan#69]
Dear Quarx,
My t-mobile defy does have green lens camera,
I updated cm7 nightly 14/7, 17/7, 19/7 and 21/7.
However, after that my camera was force close and I could not use my camera app.
Whenever I turn on camera app, it shows the screen for capture, after that it says "force close/wait..." 
So, I can not use camera app.
Pls help me with this. What should I do now? Or you can fix this problem in the next update?
Awaiting for your reply,

**Comment by killigrew** [comment]
this is no bug report!, 
please take a look in the xda forum thread and only post bug in here 
if there are more people then just you, who are having the problem.
Otherwise its more likely just a problem of your installation and not a fixable bug.
So, did you try to delete the data of the camera app?

**Comment by maniac103** [comment]
No response, closing.
If problem persists, please provide logcat output.
